#!/usr/bin/env python3
"""
Interactive setup script for Solana Coinflip .env configuration.
Run this to easily configure your environment for mainnet testing.
"""
import os
import sys
from pathlib import Path

# Add backend to path for imports
sys.path.insert(0, str(Path(__file__).parent / "backend"))

from cryptography.fernet import Fernet
from backend.game.solana_ops import generate_wallet


def print_header(text):
    """Print a formatted header."""
    print("\n" + "="*60)
    print(f"  {text}")
    print("="*60 + "\n")


def print_step(step, text):
    """Print a step."""
    print(f"[{step}] {text}")


def generate_new_wallet():
    """Generate a new Solana wallet."""
    pub, secret = generate_wallet()
    return pub, secret


def main():
    print_header("🎲 Solana Coinflip - Environment Setup")

    print("This script will help you create your .env file for mainnet testing.")
    print("You'll need:")
    print("  1. Telegram Bot Token (from @BotFather)")
    print("  2. Solana RPC URL (Helius/QuickNode/Public)")
    print("  3. House Wallet (we can generate one for you)")
    print("  4. Treasury Wallet address")
    print()

    # Check if .env already exists
    env_path = Path(__file__).parent / ".env"
    if env_path.exists():
        response = input("⚠️  .env file already exists. Overwrite? (y/N): ").strip().lower()
        if response != 'y':
            print("Aborted. Existing .env file preserved.")
            return

    config = {}

    # Step 1: Telegram Bot Token
    print_step(1, "Telegram Bot Token")
    print("Go to @BotFather on Telegram and create a new bot.")
    config['BOT_TOKEN'] = input("Enter your bot token: ").strip()

    # Step 2: RPC URL
    print_step(2, "Solana RPC URL")
    print("Choose your RPC provider:")
    print("  1. Helius (recommended) - https://helius.dev")
    print("  2. QuickNode - https://quicknode.com")
    print("  3. Public RPC (slower)")
    print("  4. Custom URL")

    rpc_choice = input("Enter choice (1-4): ").strip()

    if rpc_choice == "1":
        api_key = input("Enter your Helius API key: ").strip()
        config['RPC_URL'] = f"https://mainnet.helius-rpc.com/?api-key={api_key}"
    elif rpc_choice == "2":
        endpoint = input("Enter your QuickNode endpoint URL: ").strip()
        config['RPC_URL'] = endpoint
    elif rpc_choice == "3":
        config['RPC_URL'] = "https://api.mainnet-beta.solana.com"
        print("⚠️  Public RPC can be slow. Consider using Helius or QuickNode.")
    else:
        config['RPC_URL'] = input("Enter custom RPC URL: ").strip()

    # Step 3: House Wallet
    print_step(3, "House Wallet")
    print("The house wallet holds funds for custodial (Telegram) games.")
    print("  1. Generate new wallet (recommended for testing)")
    print("  2. Use existing wallet (enter base58 secret key)")

    wallet_choice = input("Enter choice (1-2): ").strip()

    if wallet_choice == "1":
        print("\nGenerating new wallet...")
        pub, secret = generate_new_wallet()
        config['HOUSE_WALLET_SECRET'] = secret
        print(f"\n✅ Wallet generated!")
        print(f"Public Address: {pub}")
        print(f"Secret Key: {secret[:20]}...{secret[-10:]} (hidden)")
        print(f"\n⚠️  IMPORTANT: Send at least 0.5 SOL to this address:")
        print(f"   {pub}")
        print("\nSave this address! You'll need to fund it before testing.")

        # Also use this as treasury by default
        use_same = input("\nUse same wallet for treasury (fee collection)? (Y/n): ").strip().lower()
        if use_same != 'n':
            config['TREASURY_WALLET'] = pub
        else:
            config['TREASURY_WALLET'] = input("Enter treasury wallet address: ").strip()
    else:
        config['HOUSE_WALLET_SECRET'] = input("Enter house wallet secret key (base58): ").strip()
        config['TREASURY_WALLET'] = input("Enter treasury wallet address: ").strip()

    # Step 4: Encryption Key
    print_step(4, "Encryption Key")
    print("Generating encryption key for wallet security...")
    config['ENCRYPTION_KEY'] = Fernet.generate_key().decode('utf-8')
    print("✅ Encryption key generated!")

    # Step 5: Database and API settings
    config['DB_PATH'] = "coinflip.db"
    config['API_HOST'] = "0.0.0.0"
    config['API_PORT'] = "8000"

    # Write .env file
    print_step(5, "Writing .env file")

    env_content = f"""# Solana Coinflip Configuration
# Generated by setup_env.py

# Telegram Bot Token
BOT_TOKEN={config['BOT_TOKEN']}

# Solana RPC URL
RPC_URL={config['RPC_URL']}

# House Wallet (base58 secret key)
HOUSE_WALLET_SECRET={config['HOUSE_WALLET_SECRET']}

# Treasury Wallet (public address - receives fees)
TREASURY_WALLET={config['TREASURY_WALLET']}

# Encryption Key
ENCRYPTION_KEY={config['ENCRYPTION_KEY']}

# Database
DB_PATH={config['DB_PATH']}

# API Server
API_HOST={config['API_HOST']}
API_PORT={config['API_PORT']}
"""

    with open(env_path, 'w') as f:
        f.write(env_content)

    print(f"✅ .env file created at: {env_path}")

    # Final summary
    print_header("✅ Setup Complete!")
    print("Your .env file has been created with the following configuration:")
    print(f"  • Bot Token: {config['BOT_TOKEN'][:20]}...")
    print(f"  • RPC URL: {config['RPC_URL'][:50]}...")
    print(f"  • Treasury: {config['TREASURY_WALLET']}")
    print(f"  • Database: {config['DB_PATH']}")

    print("\n📋 Next Steps:")
    print("  1. Fund your house wallet with at least 0.5 SOL")
    print("  2. Install dependencies: pip install -r requirements.txt")
    print("  3. Run the bot: cd backend && python bot.py")
    print("  4. Test on Telegram with small amounts (0.01-0.05 SOL)")
    print("\n📖 For detailed instructions, see SETUP_MAINNET.md")
    print("\nGood luck! 🎲🚀\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        print("Please check your inputs and try again.")
        sys.exit(1)
